name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Azure Container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REG_USER }}
        password: ${{ secrets.REG_PW }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY }}/${{ github.REPOSITORY_OWNER }}:latest

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ github.REPOSITORY_OWNER }}-container
        dns-name-label: ${{ github.REPOSITORY_OWNER }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY }}/${{ github.REPOSITORY_OWNER }}:latest
        registry-login-server: ${{ secrets.REGISTRY }}
        registry-username: ${{ secrets.REG_USER }}
        registry-password: ${{ secrets.REG_PW }}
        name: ${{ github.REPOSITORY_OWNER }}
        location: 'north europe'
        